# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/getting-started/

baseURL = "https://andrewbenson.github.io/benson/"
defaultContentLanguage = "en"

enableRobotsTXT = true
paginate = 10
summaryLength = 0
theme = "congo"

[outputs]
  home = ["HTML", "RSS", "JSON"]